### ISSUE TITLE
Rails 4.1+ support?

### ISSUE THREAD

**Issue by bclennox** [anykeyh/rails_db_views#1]
Is there anything in particular locking this gem to `~> 4.0.1`? I'd like to use it on a Rails 4.2 project, but the dependencies can't be resolved.

**Comment by anykeyh** [comment]
Hello!

No there's no reasons. I thought the dependency in the gemspec (>3.0) would allow you to use it with rails 4 and 4.2.

But maybe the Gemfile.lock block it. I'm still confused about how the dependencies are dones between versions. I just uploaded a new version and will make a test soon with rails 4.2.

Regards,

**Comment by anykeyh** [comment]
I just fixed the project and created an empty rails 4.2 directory and everything seems to works now,

**Comment by bclennox** [comment]
Awesome! Thank you!
