### ISSUE TITLE
Why only views?

### ISSUE THREAD

**Issue by abuisman** [anykeyh/rails_db_views#2]
Hi,

I like your gem and it works just fine for views, but ONLY for views. The reason it only works for views is that you concat the SQL from the files you have to create in `db/views` onto `CREATE VIEW ...`. 

Instead of doing this and having a gem specifically suited for views, you could transform the gem to allow running any sql after your migrations. This way you can use `CREATE FUNCTION ....` as well, or 'CREATE RECURSIVE VIEW...', etc.

It seems like you have all the code required for this already there, so it would be a small step to add other things like functions to the gem; `db/functions/...`.

Kind regards :)

**Comment by anykeyh** [comment]
Hello!

Thank's for your review!

I must confess your idea is great, I'll change the code to allow the use of this gem for others structures like function etc...

Regards,

Yacine.

**Comment by abuisman** [comment]
Hi,

Thanks for your quick response :). Great that you will look into creating other structures with your gem too.

We have been playing around in the meanwhile with looking at seeds for creating a function. The (only) problem with this is the order in which you want to create functions, views, tables, etc. Seeds have to be run after a migration, when you have and INDEX that requires a certain FUNCTION to exist you will have to make sure that the function is created before the index. Seeds run after the migration, so in our case we cannot seed the FUNCTION so it looks like it must be done in a rake task before schema loads, etc.

Just FYI ;)

**Comment by anykeyh** [comment]
I understand your need:
- You make index with value transformed by function at first, so you would be able to destroy/create functions before doing the migration (and creating then your new indexes).

But I didn't understand the seeds part, can you explain me more?

I'm planning to review the configuration code, with a DSL like structure able to append/prepend the change, able to use every type of structures etc...

Thanks!

**Comment by abuisman** [comment]
Just to avoid confusion I’ll try to explain again:

When you create an index that uses a custom function the function will have to exist before you create the index. You cannot create an index using a function that doesn’t exist. So:

```
— Pseudo code
CREATE INDEX some_index ON customers (my_function(id, e-mail));
```

This will not work if we do not create `my_function` first. Which is logical. This means that we will have to create functions BEFORE the migration. And because the database has to exist, we will have to create the functions AFTER the db rake tasks create the database.

Now for the seeds. This gem does not allow us to create functions (yet). So we decided to put the sql for creating the functions and views in seeds. Using the seed bank gem we can create a file called `views.seeds.rb` under `db/seeds`. In this we put a dependency on the `functions.seed.rb` so that we create functions before the views. These seeds will need to be ran manually on production, but they run automatically when you do `rake db:reset` on development. 

**First problem**
So far so good. BUT!: We cannot create an index using the functions we specified in `functions.seeds.rb`. This is because when running things like `rake db:reset` the migrations (or schema:load) run first and then the seeds run. An INDEX is part of the schema.rb, so that loads first. If we were to create an index that uses a function it would end up being loaded before the seeds run. Therefore, it wouldn’t work, as Postgres (or another db) would throw an error saying that the function `my_function` doesn’t exist.

To summarise for this gem: When creating FUNCTIONS make sure to do so before the migration because things like INDEX and VIEW may depend on them. Doing this in seeds will work fine for VIEW, but will not work for FUNCTION if the function is used in an INDEX.

**Hack:** Note that an ‘hack’ would be to create the index in the seeds as well, but that would be not very consistent and it would get unclear where which pieces of the database are defined.

**Second problem**
Now tests come into play and the seed setup doesn’t really work anymore. Here the same issue comes into play regarding the order in which things are created. We do not want to run all our seeds on the test database. Also, running the seeds, in our case using the seed bank gem, would require us to invoke a rake task that runs these before the test suite is run. After some issues regarding the invoking of these rake tasks, etc we decided to put the code that creates our views and functions in the `views.seeds.rb` and `functions.seeds.rb` files into plain ruby files: `views.rb` and `functions.rb` and `load` these into the seeds files and load them before the test suite runs like so:

In `rails_helper.rb`:

```
   config.before(:suite) do
      DatabaseCleaner.clean_with(:truncation)
      load ‘./db/seeds/functions.rb’
      load ‘./db/seeds/views.rb’
   end
```

This way the views and functions are always created before the test suite runs.

**Note** a side-effect of always running the create commands is that we have to keep in mind that the FUNCTION or the VIEW we are trying to create could already exist. So we use the `CREATE OR REPLACE VIEW` and `CREATE OR REPLACE FUNCTION` command instead of ‘just’ using `CREATE` in both cases.

**Comment by anykeyh** [comment]
Ok I understand well now the problem!

I'm think about managing the configurations for something like this:

(Pseudo-ruby)

``` ruby
# in config/application.rb for example
# Register your own SQL fragment manager
config.rails_sql_view.register :functions do
  apply_on_files 'db/functions/*.sql'

  # do before the migration process
  execute before: "db:migrate" do |filename, sql_fragment|
    "DROP FUNCTION IF EXISTS #{filename};"
  end

  # Here it will trigger also before database reset
  execute before: "db:migrate", after: "db:create" do |filename, sql_fragment|
    "CREATE FUNCTION #{filename} AS #{sql_fragment};"
  end

  #You can set a "after" trigger:
  execute after: "db:migrate" do |filename, sql_fragment|
    #Do nothing in your case
  end
end
```

It will keep the current system working well for views and allow you to use this gem for your function need.

I just need to check if `db:create` is used inside `db:reset`.

The order between functions and view etc... will be the same than the order of the call to the `config.rails_sql_view.register` method.

**Comment by abuisman** [comment]
Yes that looks good.

The only thing I am wondering is whether you would want to append the `CREATE ...` to the sql_fragment. Why not allow a developer to write the complete create statement himself?

One thing I had to do with the views when using the gem was rewrite my create statement. I wanted to do:

`CREATE RECURSIVE VIEW....` but I had to rewrite it to: `WITH RECURSIVE ...`

What is the added value of wrapping the SQL in the `CREATE ...`?

**Comment by abuisman** [comment]
Never mind 'REPLACE'. DROP IF EXISTS is much nicer. I just got some errors with CREATE OR REPLACE. Apparently 'REPLACE' tries some mapping of columns, etc.

Fact remains that it would be nice to not have to write the inner fragment, but being allowed to write the whole thing. This way you can also include some generic 'before_migration' and 'after_migration' directories in `db/` for more generic scripts that need to run... well before and after migrations ;).

**Comment by jkz** [comment]
After playing with this for 15 minutes and being amazed at how well this fits in the rails ecosystem and why I've never come across this pattern before, I ended up with this exact question. And started playing around with a `db/functions` folder before checking the issues on the repo.

Did you ever get to update the gem?

**Comment by anykeyh** [comment]
Hello!

I would really love to fix the gem, but I'm quite busy on others projects theses days. 
According to the fact some people think this is very useful, I'll put it in priority of my asana's free time  tasks ;-)

Otherwise, feel free to contribute, I would merge your change with pleasure.

**Comment by anykeyh** [comment]
Hey! I get some time to fix it. Now it's working with functions, and the code has been refactorized.
