### ISSUE TITLE
Migration fails after db:drop db:create - Postgres

### ISSUE THREAD

**Issue by rhryniow** [anykeyh/rails_db_views#3]
Hi,
If you create view and do full rebuild of database - as often happens in development environment the migration fails with following (used "view_name" as example):

_DROP VIEW view_name...
rake aborted!
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  view "view_name" does not exist
: DROP VIEW view_name_

Then entire migration fails and basically you are stuck as views cannot be create before the tables are there.

btw. - the same case will happen if you juste create new view and do db:migrate - unless you manually call db:create_views.

**Comment by anykeyh** [comment]
Hello, this has been fixed. I've forgotten to remove a commented block.

To avoid this again, I just added some kind of automated testing and real life example into the dummy.
