### ISSUE TITLE
creating sql views in the test database

### ISSUE THREAD

**Issue by quentic** [anykeyh/rails_db_views#4]
Hi,
Thanks for this useful project!
I'm currently using it with MySQL and it works fine on the development database. I was just wondering if it should automatically create the SQL views in the the test database when running the tests?
Or do I have to create the SQL views manually?

Christian

**Comment by anykeyh** [comment]
Hello,

It doesn't create automatically the SQL views in the test database, but instead you need to migrate with `RAIL_ENV=test rake db:migrate`

Once migrated once, it should stay forever.

Note: For now this gem doesn't track differents versions of the views, so if you change the views, you need to migrate again  or use `RAILS_ENV=test rake db:drop_views db:create_views`

**Comment by quentic** [comment]
Thanks,
It works great!
