### ISSUE TITLE
releases tag

### ISSUE THREAD

**Issue by mathieujobin** [anykeyh/rails_db_views#8]
would be great if you could tag every releases you made, so we can see them on github. and easily do compare between releases.

also, https://github.com/anykeyh/rails_db_views/blob/master/lib/rails_db_views/version.rb still says 0.0.5
while the 0.0.6 gem on rubygems is properly set to 0.0.6
which means you might have had it uncommitted locally when you made the gem.
which also means there might be other code in the gem that is not on github...

**Comment by anykeyh** [comment]
Yes, currently I'm not using Rubygems anymore as written in the `README` plus no tag on the tree.

Long time I want to improve on this side, so I'm going to industrialize the release process this month ;)
